/**
 * Auto-generated TypeScript types from Anchor IDL
 * Generated by: npx ts-node scripts/generate-types.ts
 * 
 * Anchor v0.32 naming conventions:
 * - Account data: camelCase field names
 * - Event data: snake_case field names
 * - Instruction params: camelCase field names
 * 
 * DO NOT EDIT MANUALLY - regenerate with the script above
 */

import { PublicKey } from "@solana/web3.js";
import { BN } from "@coral-xyz/anchor";

// ============ IDL Types ============

export interface AddCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  collateral_amount: BN;
  collateral_price_usd: BN;
}

export interface AddCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  delta_collateral_usd: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface AddCollateralLogV2 {
  owner: PublicKey;
  market: PublicKey;
  collateral_amount: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
}

export interface AddCollateralLogV3 {
  owner: PublicKey;
  market: PublicKey;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface AddCollateralParams {
  collateralDelta: BN;
}

export interface AddCompoundingLiquidityLog {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  amount_in: BN;
  compounding_amount_out: BN;
  fee_amount: BN;
  reward_per_lp_staked: BN;
  compounding_price_usd: BN;
  token_in_price: BN;
  token_in_price_exponent: number;
}

export interface AddCompoundingLiquidityParams {
  amountIn: BN;
  minCompoundingAmountOut: BN;
}

export interface AddCustodyParams {
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  token22: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: TokenRatios[];
  rewardThreshold: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
}

export interface AddCustodyToken22AccountParams {
  tokenAccountSpace: BN;
}

export interface AddInternalOracleParams {
  expo: number;
  lazerFeedId: number;
}

export interface AddLiquidityAndStakeLog {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  amount_in: BN;
  lp_amount_out: BN;
  fee_amount: BN;
  lp_price_usd: BN;
  token_in_price: BN;
  token_in_price_exponent: number;
}

export interface AddLiquidityAndStakeParams {
  amountIn: BN;
  minLpAmountOut: BN;
}

export interface AddLiquidityLog {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  amount_in: BN;
  lp_amount_out: BN;
  fee_amount: BN;
}

export interface AddLiquidityLogV2 {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  amount_in: BN;
  lp_amount_out: BN;
  fee_amount: BN;
  lp_price_usd: BN;
  token_in_price: BN;
  token_in_price_exponent: number;
}

export interface AddLiquidityParams {
  amountIn: BN;
  minLpAmountOut: BN;
}

export interface AddMarketParams {
  side: Side;
  correlation: boolean;
  maxPayoffBps: BN;
  permissions: MarketPermissions;
}

export interface AddPoolParams {
  name: string;
  permissions: Permissions;
  maxAumUsd: BN;
  metadataTitle: string;
  metadataSymbol: string;
  metadataUri: string;
  stakingFeeShareBps: BN;
  vpVolumeFactor: number;
  stakingFeeBoostBps: BN[];
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  thresholdUsd: BN;
}

export interface AmountAndFee {
  amount: BN;
  fee: BN;
}

export interface Assets {
  collateral: BN;
  owned: BN;
  locked: BN;
}

export interface BorrowRateParams {
  baseRate: BN;
  slope1: BN;
  slope2: BN;
  optimalUtilization: BN;
}

export interface BorrowRateState {
  currentRate: BN;
  cumulativeLockFee: BN;
  lastUpdate: BN;
}

export interface BurnAndClaimLog {
  owner: PublicKey;
  nft_mint: PublicKey;
  claim_amount: BN;
  current_timestamp: BN;
}

export interface BurnAndStakeLog {
  owner: PublicKey;
  nft_mint: PublicKey;
  token_stake: PublicKey;
  stake_amount: BN;
  current_timestamp: BN;
  last_updated_timestamp: BN;
  level: number;
  active_stake_amount: BN;
}

export interface CancelLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limit_price: BN;
  limit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  reserve_price: BN;
  reserve_price_exponent: number;
  reserve_amount: BN;
  reserve_usd: BN;
  stop_loss_price: BN;
  stop_loss_price_exponent: number;
  take_profit_price: BN;
  take_profit_price_exponent: number;
  receive_custody_uid: number;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface CancelTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  receive_custody_uid: number;
  is_stop_loss: boolean;
}

export interface CancelTriggerOrderParams {
  orderId: number;
  isStopLoss: boolean;
}

export interface CancelUnstakeTokenRequestLog {
  owner: PublicKey;
  token_stake: PublicKey;
  amount: BN;
  current_timestamp: BN;
  last_updated_timestamp: BN;
  level: number;
  active_stake_amount: BN;
}

export interface CancelUnstakeTokenRequestParams {
  withdrawRequestId: number;
}

export interface CloseAndSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  receive_custody_uid: BN;
  receive_amount: BN;
  swap_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface CloseAndSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  exit_fee_usd: BN;
  output_custody_uid: number;
  output_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  price_impact_usd: BN;
  padding: BN[];
}

export interface CloseAndSwapParams {
  priceWithSlippage: ContractOraclePrice;
  privilege: Privilege;
}

export interface ClosePositionLog {
  owner: PublicKey;
  market: PublicKey;
  price_usd: BN;
  size_amount: BN;
  size_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
}

export interface ClosePositionLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  exit_fee_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  price_impact_usd: BN;
  padding: BN[];
}

export interface ClosePositionLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
}

export interface ClosePositionLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface ClosePositionParams {
  priceWithSlippage: ContractOraclePrice;
  privilege: Privilege;
}

export interface CollectRebateLog {
  owner: PublicKey;
  token_stake: PublicKey;
  rebate_amount: BN;
  rebate_usd: BN;
  padding: BN[];
}

export interface CollectRevenueLog {
  owner: PublicKey;
  token_stake: PublicKey;
  revenue_amount: BN;
  last_epoch_count: number;
  padding: BN[];
}

export interface CollectRevenueParams {
}

export interface CollectStakeRewardLog {
  owner: PublicKey;
  pool_name: string;
  reward_amount: BN;
  reward_mint: PublicKey;
}

export interface CollectStakeRewardLogV2 {
  owner: PublicKey;
  pool_name: string;
  reward_amount: BN;
  reward_mint: PublicKey;
  reward_share: BN;
}

export interface CollectStakeRewardParams {
}

export interface CollectTokenRewardLog {
  owner: PublicKey;
  token_stake: PublicKey;
  amount: BN;
  last_epoch_count: number;
  padding: BN[];
}

export interface CollectTokenRewardParams {
}

export interface CompoundFeesParams {
}

export interface CompoundingFeesLog {
  pool_name: string;
  reward_amount: BN;
  reward_lp_amount: BN;
  reward_per_lp_staked: BN;
  lp_price_usd: BN;
  compounding_price_usd: BN;
}

export interface CompoundingStats {
  activeAmount: BN;
  totalSupply: BN;
  rewardSnapshot: BN;
  feeShareBps: BN;
  lastCompoundTime: BN;
}

export interface CompoundingTokenData {
  lpPrice: BN;
  compoundingPrice: BN;
  ratios: BN[];
}

export interface CreateReferralParams {
}

export interface CreateWhitelistParams {
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  poolAddress: PublicKey;
}

export interface Custody {
  pool: PublicKey;
  mint: PublicKey;
  tokenAccount: PublicKey;
  decimals: number;
  isStable: boolean;
  depegAdjustment: boolean;
  isVirtual: boolean;
  inversePrice: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  rewardThreshold: BN;
  assets: Assets;
  feesStats: FeesStats;
  borrowRateState: BorrowRateState;
  bump: number;
  tokenAccountBump: number;
  token22: boolean;
  uid: number;
  reservedAmount: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  padding: number[];
}

export interface CustomOracle {
  price: BN;
  expo: number;
  conf: BN;
  ema: BN;
  publishTime: BN;
  lazerFeedId: number;
  lazerPrice: BN;
  Reserved: number[];
}

export interface DecreaseSizeLog {
  owner: PublicKey;
  market: PublicKey;
  price_usd: BN;
  size_delta: BN;
  size_delta_usd: BN;
  settled_returns: BN;
  delta_profit_usd: BN;
  delta_loss_usd: BN;
  fee_amount: BN;
}

export interface DecreaseSizeLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  exit_fee_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  price_impact_usd: BN;
  padding: BN[];
}

export interface DecreaseSizeLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_delta: BN;
  size_delta_usd: BN;
  settled_returns: BN;
  delta_profit_usd: BN;
  delta_loss_usd: BN;
  fee_amount: BN;
}

export interface DecreaseSizeLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface DecreaseSizeParams {
  priceWithSlippage: ContractOraclePrice;
  sizeDelta: BN;
  privilege: Privilege;
}

export interface DepositStakeLog {
  pool_name: string;
  owner: PublicKey;
  lp_tokens: BN;
}

export interface DepositStakeParams {
  depositAmount: BN;
}

export interface DepositTokenStakeLog {
  owner: PublicKey;
  token_stake: PublicKey;
  deposit_amount: BN;
  current_timestamp: BN;
  last_updated_timestamp: BN;
  level: number;
  active_stake_amount: BN;
}

export interface DepositTokenStakeParams {
  depositAmount: BN;
}

export interface DistributeTokenRewardLog {
  amount: BN;
  epoch_count: number;
  padding: BN[];
}

export interface DistributeTokenRewardParams {
  amount: BN;
  epochCount: number;
}

export interface EditLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limit_price: BN;
  limit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  reserve_price: BN;
  reserve_price_exponent: number;
  reserve_amount: BN;
  reserve_usd: BN;
  stop_loss_price: BN;
  stop_loss_price_exponent: number;
  take_profit_price: BN;
  take_profit_price_exponent: number;
  receive_custody_uid: number;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface EditLimitOrderParams {
  orderId: number;
  limitPrice: ContractOraclePrice;
  sizeAmount: BN;
  stopLossPrice: ContractOraclePrice;
  takeProfitPrice: ContractOraclePrice;
}

export interface EditTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  receive_custody_uid: number;
  is_stop_loss: boolean;
}

export interface EditTriggerOrderParams {
  orderId: number;
  triggerPrice: ContractOraclePrice;
  deltaSizeAmount: BN;
  isStopLoss: boolean;
}

export interface ExecuteLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
}

export interface ExecuteLimitOrderLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  delta_collateral_usd: BN;
  final_collateral_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  entry_fee_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
  padding: BN[];
}

export interface ExecuteLimitOrderLogV2 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  entry_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
  fee_rebate_usd_amount: BN;
  padding: BN[];
}

export interface ExecuteLimitOrderParams {
  orderId: number;
  privilege: Privilege;
}

export interface ExecuteLimitWithSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  reserve_custody_uid: BN;
  reserve_amount: BN;
  swap_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
}

export interface ExecuteLimitWithSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  reserve_custody_uid: number;
  reserve_price: BN;
  reserve_price_exponent: number;
  reserve_amount: BN;
  delta_collateral_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  entry_fee_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
  padding: BN[];
}

export interface ExecuteLimitWithSwapLogV2 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  entry_fee_amount: BN;
  reserve_custody_uid: BN;
  reserve_amount: BN;
  swap_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  limit_price: BN;
  limit_price_exponent: number;
  fee_rebate_amount: BN;
  padding: BN[];
}

export interface ExecuteLimitWithSwapParams {
  orderId: number;
  privilege: Privilege;
}

export interface ExecuteTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  is_stop_loss: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  trigger_price: BN;
  trigger_price_exponent: number;
}

export interface ExecuteTriggerOrderLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  exit_fee_usd: BN;
  out_amount: BN;
  is_stop_loss: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  trigger_price: BN;
  trigger_price_exponent: number;
  price_impact_usd: BN;
  padding: BN[];
}

export interface ExecuteTriggerOrderParams {
  isStopLoss: boolean;
  orderId: number;
  privilege: Privilege;
}

export interface ExecuteTriggerWithSwapLog {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  is_stop_loss: boolean;
  receive_custody_uid: BN;
  receive_amount: BN;
  swap_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  trigger_price: BN;
  trigger_price_exponent: number;
}

export interface ExecuteTriggerWithSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  exit_fee_usd: BN;
  out_custody_uid: number;
  out_amount: BN;
  is_stop_loss: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  trigger_price: BN;
  trigger_price_exponent: number;
  price_impact_usd: BN;
  padding: BN[];
}

export interface ExecuteTriggerWithSwapParams {
  isStopLoss: boolean;
  orderId: number;
  privilege: Privilege;
}

export interface Fees {
  mode: FeesMode;
  swapIn: RatioFees;
  swapOut: RatioFees;
  stableSwapIn: RatioFees;
  stableSwapOut: RatioFees;
  addLiquidity: RatioFees;
  removeLiquidity: RatioFees;
  openPosition: BN;
  closePosition: BN;
  volatility: BN;
}

export type FeesMode = { fixed: Record<string, never> } | { linear: Record<string, never> };

export interface FeesStats {
  accrued: BN;
  distributed: BN;
  paid: BN;
  rewardPerLpStaked: BN;
  protocolFee: BN;
}

export interface FlpStake {
  owner: PublicKey;
  pool: PublicKey;
  stakeStats: StakeStats;
  rewardSnapshot: BN;
  unclaimedRewards: BN;
  feeShareBps: BN;
  isInitialized: number;
  bump: number;
}

export interface GetAddCompoundingLiquidityAmountAndFeeParams {
  amountIn: BN;
}

export interface GetAddLiquidityAmountAndFeeParams {
  amountIn: BN;
}

export interface GetAssetsUnderManagementParams {
}

export interface GetCompoundingTokenDataParams {
}

export interface GetCompoundingTokenPriceParams {
}

export interface GetEntryPriceAndFeeParams {
  collateral: BN;
  size: BN;
  side: Side;
}

export interface GetExitPriceAndFeeParams {
}

export interface GetLiquidationPriceParams {
}

export interface GetLiquidationStateParams {
}

export interface GetLpTokenPriceParams {
}

export interface GetOraclePriceParams {
}

export interface GetPnlParams {
}

export interface GetPositionDataParams {
}

export interface GetRemoveCompoundingLiquidityAmountAndFeeParams {
  compoundingAmountIn: BN;
}

export interface GetRemoveLiquidityAmountAndFeeParams {
  lpAmountIn: BN;
}

export interface GetSwapAmountAndFeesParams {
  amountIn: BN;
}

export interface IncreaseSizeLog {
  owner: PublicKey;
  market: PublicKey;
  price_usd: BN;
  size_amount: BN;
  size_usd: BN;
  fee_amount: BN;
}

export interface IncreaseSizeLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  final_collateral_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  entry_fee_usd: BN;
  is_degen: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface IncreaseSizeLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  fee_amount: BN;
}

export interface IncreaseSizeLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface IncreaseSizeLogV4 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  delta_size_amount: BN;
  delta_size_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  entry_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  is_degen: boolean;
  padding: number[];
}

export interface IncreaseSizeParams {
  priceWithSlippage: ContractOraclePrice;
  sizeDelta: BN;
  privilege: Privilege;
}

export interface InitCompoundingParams {
  feeShareBps: BN;
  metadataTitle: string;
  metadataSymbol: string;
  metadataUri: string;
}

export interface InitParams {
  minSignatures: number;
  permissions: Permissions;
  voltageMultiplier: VoltageMultiplier;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
}

export interface InitRebateVaultParams {
  allowRebatePayout: boolean;
}

export interface InitRevenueTokenAccountParams {
  feeShareBps: BN;
}

export interface InitStakingParams {
  stakingFeeShareBps: BN;
}

export interface InitTokenVaultParams {
  tokenPermissions: TokenPermissions;
  amount: BN;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  stakeLevel: BN[];
}

export interface InternalEmaPrice {
  emaPrice: BN;
  publishTime: BN;
}

export interface InternalPrice {
  price: BN;
  conf: BN;
  publishTime: BN;
}

export interface LimitOrder {
  limitPrice: ContractOraclePrice;
  reserveAmount: BN;
  reserveCustodyUid: number;
  receiveCustodyUid: number;
  sizeAmount: BN;
  stopLossPrice: ContractOraclePrice;
  takeProfitPrice: ContractOraclePrice;
}

export interface LiquidateLog {
  owner: PublicKey;
  market: PublicKey;
  price_usd: BN;
  size_usd: BN;
  size_amount: BN;
  fee_amount: BN;
}

export interface LiquidateLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_usd: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_usd: BN;
  penalty_usd: BN;
  exit_fee_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface LiquidateLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_usd: BN;
  size_amount: BN;
  fee_amount: BN;
}

export interface LiquidateLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  duration: BN;
  exit_price: BN;
  exit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  profit_usd: BN;
  loss_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  exit_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface LiquidateParams {
}

export interface Market {
  pool: PublicKey;
  targetCustody: PublicKey;
  collateralCustody: PublicKey;
  side: Side;
  correlation: boolean;
  maxPayoffBps: BN;
  permissions: MarketPermissions;
  degenExposureUsd: BN;
  collectivePosition: PositionStats;
  targetCustodyUid: number;
  padding: number[];
  collateralCustodyUid: number;
  padding2: number[];
  bump: number;
}

export interface MarketPermissions {
  allowOpenPosition: boolean;
  allowClosePosition: boolean;
  allowCollateralWithdrawal: boolean;
  allowSizeChange: boolean;
}

export interface MigrateFlpLog {
  pool_name: string;
  owner: PublicKey;
  amount: BN;
  lp_amount_out: BN;
  reward_lp_amount: BN;
  reward_per_lp_staked: BN;
  lp_price_usd: BN;
  compounding_price_usd: BN;
}

export interface MigrateFlpParams {
  compoundingTokenAmount: BN;
}

export interface MigratePositionLog {
  owner: PublicKey;
  market: PublicKey;
  position: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_amount: BN;
  collateral_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
}

export interface MigrateStakeLog {
  pool_name: string;
  owner: PublicKey;
  amount: BN;
  compounding_amount_out: BN;
  pool_lp_amount: BN;
  reward_per_lp_staked: BN;
  lp_price_usd: BN;
  compounding_price_usd: BN;
}

export interface MigrateStakeParams {
  amount: BN;
}

export interface MoveProtocolFeesLog {
  pool_name: string;
  revenue_amount: BN;
  protocol_fee: BN;
  revenue_fee_share: BN;
  padding: BN[];
}

export interface Multisig {
  numSigners: number;
  numSigned: number;
  minSignatures: number;
  instructionAccountsLen: number;
  instructionDataLen: number;
  instructionHash: BN;
  signers: PublicKey[];
  signed: number[];
  bump: number;
}

export interface NewPositionPricesAndFee {
  entryPrice: ContractOraclePrice;
  feeUsd: BN;
}

export interface OpenPositionLog {
  owner: PublicKey;
  market: PublicKey;
  price_usd: BN;
  size_amount: BN;
  size_usd: BN;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
}

export interface OpenPositionLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  input_amount: BN;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  entry_fee_usd: BN;
  is_degen: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface OpenPositionLogV2 {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
}

export interface OpenPositionLogV3 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface OpenPositionLogV4 {
  owner: PublicKey;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_amount: BN;
  collateral_usd: BN;
  fee_amount: BN;
  fee_rebate_amount: BN;
  entry_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  is_degen: boolean;
  padding: number[];
}

export interface OpenPositionParams {
  priceWithSlippage: ContractOraclePrice;
  collateralAmount: BN;
  sizeAmount: BN;
  privilege: Privilege;
}

export interface OracleParams {
  intOracleAccount: PublicKey;
  extOracleAccount: PublicKey;
  oracleType: OracleType;
  maxDivergenceBps: BN;
  maxConfBps: BN;
  maxPriceAgeSec: number;
  maxBackupAgeSec: number;
}

export interface ContractOraclePrice {
  price: BN;
  exponent: number;
}

export type OracleType = { none: Record<string, never> } | { custom: Record<string, never> } | { pyth: Record<string, never> };

export interface Order {
  owner: PublicKey;
  market: PublicKey;
  limitOrders: LimitOrder[];
  takeProfitOrders: TriggerOrder[];
  stopLossOrders: TriggerOrder[];
  isInitialised: boolean;
  openOrders: number;
  openSl: number;
  openTp: number;
  inactiveSl: number;
  inactiveTp: number;
  activeOrders: number;
  bump: number;
  referenceTimestamp: BN;
  executionCount: BN;
  padding: BN[];
}

export interface Permissions {
  allowSwap: boolean;
  allowAddLiquidity: boolean;
  allowRemoveLiquidity: boolean;
  allowOpenPosition: boolean;
  allowClosePosition: boolean;
  allowCollateralWithdrawal: boolean;
  allowSizeChange: boolean;
  allowLiquidation: boolean;
  allowLpStaking: boolean;
  allowFeeDistribution: boolean;
  allowUngatedTrading: boolean;
  allowFeeDiscounts: boolean;
  allowReferralRebates: boolean;
}

export interface Perpetuals {
  permissions: Permissions;
  pools: PublicKey[];
  collections: PublicKey[];
  voltageMultiplier: VoltageMultiplier;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
  inceptionTime: BN;
  transferAuthorityBump: number;
  perpetualsBump: number;
  tradeLimit: number;
  triggerOrderLimit: number;
  rebateLimitUsd: number;
}

export interface PlaceLimitOrderLog {
  owner: PublicKey;
  market: PublicKey;
  limit_price: BN;
  limit_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  reserve_price: BN;
  reserve_price_exponent: number;
  reserve_amount: BN;
  reserve_usd: BN;
  stop_loss_price: BN;
  stop_loss_price_exponent: number;
  take_profit_price: BN;
  take_profit_price_exponent: number;
  receive_custody_uid: number;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface PlaceLimitOrderParams {
  limitPrice: ContractOraclePrice;
  reserveAmount: BN;
  sizeAmount: BN;
  stopLossPrice: ContractOraclePrice;
  takeProfitPrice: ContractOraclePrice;
}

export interface PlaceTriggerOrderLog {
  owner: PublicKey;
  market: PublicKey;
  price: BN;
  price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  receive_custody_uid: number;
  is_stop_loss: boolean;
}

export interface PlaceTriggerOrderParams {
  triggerPrice: ContractOraclePrice;
  deltaSizeAmount: BN;
  isStopLoss: boolean;
}

export interface Pool {
  name: string;
  permissions: Permissions;
  inceptionTime: BN;
  lpMint: PublicKey;
  oracleAuthority: PublicKey;
  stakedLpVault: PublicKey;
  rewardCustody: PublicKey;
  custodies: PublicKey[];
  ratios: TokenRatios[];
  markets: PublicKey[];
  maxAumUsd: BN;
  buffer: BN;
  rawAumUsd: BN;
  equityUsd: BN;
  totalStaked: StakeStats;
  stakingFeeShareBps: BN;
  bump: number;
  lpMintBump: number;
  stakedLpVaultBump: number;
  vpVolumeFactor: number;
  uniqueCustodyCount: number;
  padding: number[];
  stakingFeeBoostBps: BN[];
  compoundingMint: PublicKey;
  compoundingLpVault: PublicKey;
  compoundingStats: CompoundingStats;
  compoundingMintBump: number;
  compoundingLpVaultBump: number;
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  lpPrice: BN;
  compoundingLpPrice: BN;
  lastUpdatedTimestamp: BN;
  feesObligationUsd: BN;
  rebateObligationUsd: BN;
  thresholdUsd: BN;
}

export interface Position {
  owner: PublicKey;
  market: PublicKey;
  delegate: PublicKey;
  openTime: BN;
  updateTime: BN;
  entryPrice: ContractOraclePrice;
  sizeAmount: BN;
  sizeUsd: BN;
  lockedAmount: BN;
  lockedUsd: BN;
  priceImpactUsd: BN;
  collateralUsd: BN;
  unsettledValueUsd: BN;
  unsettledFeesUsd: BN;
  cumulativeLockFeeSnapshot: BN;
  degenSizeUsd: BN;
  referencePrice: ContractOraclePrice;
  buffer: number[];
  priceImpactSet: number;
  sizeDecimals: number;
  lockedDecimals: number;
  collateralDecimals: number;
  bump: number;
  padding: number[];
}

export interface PositionData {
  collateralUsd: BN;
  profitUsd: BN;
  lossUsd: BN;
  feeUsd: BN;
  leverage: BN;
  liquidationPrice: ContractOraclePrice;
}

export interface PositionStats {
  openPositions: BN;
  updateTime: BN;
  averageEntryPrice: ContractOraclePrice;
  sizeAmount: BN;
  sizeUsd: BN;
  lockedAmount: BN;
  lockedUsd: BN;
  collateralAmount: BN;
  collateralLiabilityUsd: BN;
  unsettledFeeUsd: BN;
  cumulativeLockFeeSnapshot: BN;
  sizeDecimals: number;
  lockedDecimals: number;
  collateralDecimals: number;
}

export interface PriceAndFee {
  price: ContractOraclePrice;
  feeUsd: BN;
}

export interface PricingParams {
  tradeSpreadMin: BN;
  tradeSpreadMax: BN;
  swapSpread: BN;
  minInitLeverage: number;
  minInitDegenLeverage: number;
  maxInitLeverage: number;
  maxInitDegenLeverage: number;
  maxLeverage: number;
  maxDegenLeverage: number;
  minCollateralUsd: number;
  minDegenCollateralUsd: number;
  delaySeconds: BN;
  maxUtilization: number;
  degenPositionFactor: number;
  degenExposureFactor: number;
  maxPositionSizeUsd: BN;
  maxExposureUsd: BN;
}

export type Privilege = { none: Record<string, never> } | { stake: Record<string, never> } | { referral: Record<string, never> };

export interface ProfitAndLoss {
  profit: BN;
  loss: BN;
}

export interface ProtocolVault {
  key: PublicKey;
  tokenAccount: PublicKey;
  isInitialized: boolean;
  bump: number;
  tokenAccountBump: number;
  feeShareBps: BN;
  feeAmount: BN;
  padding: BN[];
}

export interface RatioFees {
  minFee: BN;
  targetFee: BN;
  maxFee: BN;
}

export interface RebateVault {
  key: PublicKey;
  tokenAccount: PublicKey;
  isInitialized: boolean;
  allowPayout: boolean;
  bump: number;
  tokenAccountBump: number;
  availableUsd: BN;
  availableAmount: BN;
  padding: BN[];
}

export interface Referral {
  isInitialized: boolean;
  bump: number;
  refererTokenStakeAccount: PublicKey;
  refererBoosterAccount: PublicKey;
  padding: BN[];
}

export interface ReferralRebateLog {
  token_stake: PublicKey;
  owner: PublicKey;
  rebate_usd: BN;
  volume_usd: BN;
  voltage_points_type: number;
  padding: BN[];
}

export interface RefreshStakeLog {
  pool_name: string;
  reward_per_lp_staked: BN;
}

export interface RefreshStakeParams {
}

export interface RefreshStakeUserLog {
  owner: PublicKey;
  pool_name: string;
  reward_amount: BN;
  reward_mint: PublicKey;
  reward_share: BN;
}

export interface RefreshTokenStakeLog {
  revenue_per_faf_staked: BN;
}

export interface RefreshTokenStakeParams {
}

export interface RefreshTokenStakeUserLog {
  owner: PublicKey;
  revenue_amount: BN;
  newly_unlocked_amount: BN;
}

export interface ReimburseParams {
  amountIn: BN;
}

export interface RemoveCollateralAndSwapLog {
  owner: PublicKey;
  market: PublicKey;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  receive_custody_uid: BN;
  receive_amount: BN;
  swap_fee_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface RemoveCollateralAndSwapLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_usd: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  receive_custody_uid: number;
  receive_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface RemoveCollateralAndSwapParams {
  collateralDeltaUsd: BN;
}

export interface RemoveCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  collateral_amount: BN;
  collateral_price_usd: BN;
}

export interface RemoveCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_usd: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  receive_amount: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface RemoveCollateralLogV2 {
  owner: PublicKey;
  market: PublicKey;
  collateral_amount: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
}

export interface RemoveCollateralLogV3 {
  owner: PublicKey;
  market: PublicKey;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface RemoveCollateralParams {
  collateralDeltaUsd: BN;
}

export interface RemoveCompoundingLiquidityLog {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  compounding_amount_in: BN;
  amount_out: BN;
  fee_amount: BN;
  reward_per_lp_staked: BN;
  compounding_price_usd: BN;
  token_out_price: BN;
  token_out_price_exponent: number;
}

export interface RemoveCompoundingLiquidityParams {
  compoundingAmountIn: BN;
  minAmountOut: BN;
}

export interface RemoveCustodyParams {
  ratios: TokenRatios[];
}

export interface RemoveLiquidityLog {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  lp_amount_in: BN;
  amount_out: BN;
  fee_amount: BN;
}

export interface RemoveLiquidityLogV2 {
  pool_name: string;
  owner: PublicKey;
  custody_uid: BN;
  lp_amount_in: BN;
  amount_out: BN;
  fee_amount: BN;
  lp_price_usd: BN;
  token_out_price: BN;
  token_out_price_exponent: number;
}

export interface RemoveLiquidityParams {
  lpAmountIn: BN;
  minAmountOut: BN;
}

export interface RemoveMarketParams {
}

export interface RemovePoolParams {
}

export interface RenameFlpParams {
  flag: BN;
  lpTokenName: string;
  lpTokenSymbol: string;
  lpTokenUri: string;
}

export interface ResizeInternalOracleParams {
  lazerFeedId: number;
}

export interface SetAdminSignersParams {
  minSignatures: number;
}

export interface SetCustodyConfigParams {
  depegAdjustment: boolean;
  inversePrice: boolean;
  oracle: OracleParams;
  pricing: PricingParams;
  permissions: Permissions;
  fees: Fees;
  borrowRate: BorrowRateParams;
  ratios: TokenRatios[];
  rewardThreshold: BN;
  minReserveUsd: BN;
  limitPriceBufferBps: BN;
  token22: boolean;
}

export interface SetCustomOraclePriceParams {
  price: BN;
  expo: number;
  conf: BN;
  ema: BN;
  publishTime: BN;
}

export interface SetFeeShareParams {
  feeShareBps: BN;
}

export interface SetInternalCurrentPriceParams {
  useCurrentTime: number;
  prices: InternalPrice[];
}

export interface SetInternalEmaPriceParams {
  prices: InternalEmaPrice[];
}

export interface SetInternalLazerPriceParams {
  messageData: number[];
}

export interface SetLpTokenPriceParams {
}

export interface SetMarketConfigParams {
  maxPayoffBps: BN;
  permissions: MarketPermissions;
  correlation: boolean;
}

export interface SetPermissionsParams {
  permissions: Permissions;
}

export interface SetPerpetualsConfigParams {
  allowUngatedTrading: boolean;
  tradingDiscount: BN[];
  referralRebate: BN[];
  defaultRebate: BN;
  voltageMultiplier: VoltageMultiplier;
  tradeLimit: number;
  triggerOrderLimit: number;
  rebateLimitUsd: number;
}

export interface SetPoolConfigParams {
  permissions: Permissions;
  oracleAuthority: PublicKey;
  maxAumUsd: BN;
  stakingFeeShareBps: BN;
  vpVolumeFactor: number;
  stakingFeeBoostBps: BN[];
  minLpPriceUsd: BN;
  maxLpPriceUsd: BN;
  thresholdUsd: BN;
}

export interface SetPositionPriceImpactLog {
  position: PublicKey;
  market: PublicKey;
  price_impact_usd: BN;
  padding: BN[];
}

export interface SetPositionPriceImpactParams {
  priceImpactUsd: BN;
}

export interface SetProtocolFeeShareParams {
  feeShareBps: BN;
}

export interface SetTestTimeParams {
  time: BN;
}

export interface SetTokenRewardLog {
  token_stake: PublicKey;
  amount: BN;
  epoch_count: number;
  padding: BN[];
}

export interface SetTokenRewardParams {
  amount: BN;
  epochCount: number;
}

export interface SetTokenStakeLevelParams {
  level: number;
  init: boolean;
}

export interface SetTokenVaultConfigParams {
  tokenPermissions: TokenPermissions;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  stakeLevel: BN[];
  unlockPeriod: BN;
}

export interface SetWhitelistConfigParams {
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  poolAddress: PublicKey;
}

export interface SettleRebatesLog {
  pool_name: string;
  rebate_usd: BN;
  rebate_amount: BN;
  padding: BN[];
}

export type Side = { none: Record<string, never> } | { long: Record<string, never> } | { short: Record<string, never> };

export interface StakeStats {
  pendingActivation: BN;
  activeAmount: BN;
  pendingDeactivation: BN;
  deactivatedAmount: BN;
}

export interface SwapAmountAndFees {
  amountOut: BN;
  feeIn: BN;
  feeOut: BN;
}

export interface SwapAndAddCollateralLog {
  owner: PublicKey;
  market: PublicKey;
  receiving_custody_uid: BN;
  receive_amount: BN;
  swap_fee_amount: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  delta_collateral_amount: BN;
  final_collateral_amount: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
}

export interface SwapAndAddCollateralLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  input_custody_uid: number;
  input_price: BN;
  input_price_exponent: number;
  delta_input_amount: BN;
  delta_collateral_usd: BN;
  final_collateral_usd: BN;
  final_size_amount: BN;
  final_size_usd: BN;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface SwapAndAddCollateralParams {
  amountIn: BN;
}

export interface SwapAndOpenLog {
  pool_name: string;
  owner: PublicKey;
  receiving_custody_uid: BN;
  collateral_custody_uid: BN;
  target_custody_uid: BN;
  amount_in: BN;
  swap_amount_out: BN;
  swap_fee_amount: BN;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  position_fee_amount: BN;
  fee_rebate_amount: BN;
  receiving_oracle_account_time: BN;
  receiving_oracle_account_type: number;
  receiving_oracle_account_price: BN;
  receiving_oracle_account_price_exponent: number;
  collateral_oracle_account_time: BN;
  collateral_oracle_account_type: number;
  collateral_oracle_account_price: BN;
  collateral_oracle_account_price_exponent: number;
  target_oracle_account_time: BN;
  target_oracle_account_type: number;
  target_oracle_account_price: BN;
  target_oracle_account_price_exponent: number;
}

export interface SwapAndOpenLogUSDv1 {
  owner: PublicKey;
  market: PublicKey;
  trade_id: BN;
  input_custody_uid: number;
  input_price: BN;
  input_price_exponent: number;
  input_amount: BN;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_usd: BN;
  fee_usd: BN;
  rebate_usd: BN;
  discount_usd: BN;
  entry_fee_usd: BN;
  is_degen: boolean;
  oracle_account_time: BN;
  oracle_account_type: number;
  oracle_account_price: BN;
  oracle_account_price_exponent: number;
  padding: BN[];
}

export interface SwapAndOpenLogV2 {
  pool_name: string;
  owner: PublicKey;
  receiving_custody_uid: BN;
  collateral_custody_uid: BN;
  target_custody_uid: BN;
  amount_in: BN;
  swap_amount_out: BN;
  swap_fee_amount: BN;
  market: PublicKey;
  entry_price: BN;
  entry_price_exponent: number;
  size_amount: BN;
  size_usd: BN;
  collateral_price: BN;
  collateral_price_exponent: number;
  collateral_amount: BN;
  collateral_usd: BN;
  position_fee_amount: BN;
  fee_rebate_amount: BN;
  entry_fee_amount: BN;
  receiving_oracle_account_time: BN;
  receiving_oracle_account_type: number;
  receiving_oracle_account_price: BN;
  receiving_oracle_account_price_exponent: number;
  collateral_oracle_account_time: BN;
  collateral_oracle_account_type: number;
  collateral_oracle_account_price: BN;
  collateral_oracle_account_price_exponent: number;
  target_oracle_account_time: BN;
  target_oracle_account_type: number;
  target_oracle_account_price: BN;
  target_oracle_account_price_exponent: number;
  is_degen: boolean;
  padding: number[];
}

export interface SwapAndOpenParams {
  priceWithSlippage: ContractOraclePrice;
  amountIn: BN;
  sizeAmount: BN;
  privilege: Privilege;
}

export interface SwapFeeInternalLog {
  pool_name: string;
  owner: PublicKey;
  custody_in_uid: BN;
  custody_out_uid: BN;
  swap_amount: BN;
  reward_custody_amount: BN;
}

export interface SwapFeeInternalLogV2 {
  pool_name: string;
  owner: PublicKey;
  custody_in_uid: BN;
  custody_out_uid: BN;
  swap_amount: BN;
  reward_custody_amount: BN;
  in_oracle_account_time: BN;
  in_oracle_account_type: number;
  in_oracle_account_price: BN;
  in_oracle_account_price_exponent: number;
  out_oracle_account_time: BN;
  out_oracle_account_type: number;
  out_oracle_account_price: BN;
  out_oracle_account_price_exponent: number;
}

export interface SwapFeeInternalLogV3 {
  pool_name: string;
  owner: PublicKey;
  fee_amount: BN;
  padding: BN[];
}

export interface SwapFeeInternalParams {
}

export interface SwapLog {
  pool_name: string;
  owner: PublicKey;
  custody_in_uid: BN;
  custody_out_uid: BN;
  amount_in: BN;
  amount_out: BN;
  fee_in_amount: BN;
  fee_out_amount: BN;
}

export interface SwapLogV2 {
  pool_name: string;
  owner: PublicKey;
  custody_in_uid: BN;
  custody_out_uid: BN;
  amount_in: BN;
  amount_out: BN;
  fee_in_amount: BN;
  fee_out_amount: BN;
  in_oracle_account_time: BN;
  in_oracle_account_type: number;
  in_oracle_account_price: BN;
  in_oracle_account_price_exponent: number;
  out_oracle_account_time: BN;
  out_oracle_account_type: number;
  out_oracle_account_price: BN;
  out_oracle_account_price_exponent: number;
}

export interface SwapParams {
  amountIn: BN;
  minAmountOut: BN;
}

export interface TestInitParams {
  minSignatures: number;
  permissions: Permissions;
}

export interface TokenPermissions {
  allowDeposits: boolean;
  allowWithdrawal: boolean;
  allowRewardWithdrawal: boolean;
}

export interface TokenRatios {
  target: BN;
  min: BN;
  max: BN;
}

export interface TokenStake {
  owner: PublicKey;
  isInitialized: boolean;
  bump: number;
  level: number;
  withdrawRequestCount: number;
  withdrawRequest: WithdrawRequest[];
  buffer: number[];
  activeStakeAmount: BN;
  updateTimestamp: BN;
  tradeTimestamp: BN;
  tradeCounter: number;
  lastRewardEpochCount: number;
  rewardTokens: BN;
  unclaimedRevenueAmount: BN;
  revenueSnapshot: BN;
  claimableRebateUsd: BN;
}

export interface TokenStakeStats {
  lockedAmount: BN;
  activeAmount: BN;
  withdrawableAmount: BN;
  buffer: BN;
}

export interface TokenVault {
  isInitialized: boolean;
  bump: number;
  tokenAccountBump: number;
  tokenMint: PublicKey;
  tokenVaultTokenAccount: PublicKey;
  tokenPermissions: TokenPermissions;
  withdrawTimeLimit: BN;
  withdrawInstantFee: BN;
  withdrawInstantFeeEarned: BN;
  stakeLevel: BN[];
  tokensStaked: TokenStakeStats;
  rewardTokensToDistribute: BN;
  rewardTokensPaid: BN;
  tokensToDistribute: BN;
  tokensDistributed: BN;
  lastRewardEpochCount: number;
  rewardTokensDistributed: BN;
  padding: number[];
  revenueTokenAccountBump: number;
  revenuePerFafStaked: BN;
  revenueAccrued: BN;
  revenueDistributed: BN;
  revenuePaid: BN;
  unlockPeriod: BN;
  padding2: BN[];
}

export interface TriggerOrder {
  triggerPrice: ContractOraclePrice;
  triggerSize: BN;
  receiveCustodyUid: number;
}

export interface UnstakeInstantLog {
  pool_name: string;
  owner: PublicKey;
  unstake_amount: BN;
  reward_per_lp_staked: BN;
}

export interface UnstakeInstantParams {
  unstakeAmount: BN;
}

export interface UnstakeRequestLog {
  pool_name: string;
  owner: PublicKey;
  amount: BN;
}

export interface UnstakeRequestParams {
  unstakeAmount: BN;
}

export interface UnstakeTokenRequestLog {
  owner: PublicKey;
  token_stake: PublicKey;
  unstake_amount: BN;
  current_timestamp: BN;
  last_updated_timestamp: BN;
  level: number;
  active_stake_amount: BN;
}

export interface UnstakeTokenRequestParams {
  unstakeAmount: BN;
}

export interface VoltageMultiplier {
  volume: BN;
  rewards: BN;
  rebates: BN;
}

export interface VoltagePointsLog {
  token_stake: PublicKey;
  voltage_points: BN;
  rebate_usd: BN;
  voltage_points_type: number;
  padding: BN[];
}

export interface Whitelist {
  owner: PublicKey;
  isInitialized: boolean;
  bump: number;
  isSwapFeeExempt: boolean;
  isDepositFeeExempt: boolean;
  isWithdrawalFeeExempt: boolean;
  buffer: number[];
  pool: PublicKey;
}

export interface WithdrawFeesParams {
}

export interface WithdrawInstantFeesParams {
}

export interface WithdrawRequest {
  withdrawableAmount: BN;
  lockedAmount: BN;
  timeRemaining: BN;
}

export interface WithdrawSolFeesParams {
  amount: BN;
}

export interface WithdrawStakeLog {
  pool_name: string;
  owner: PublicKey;
  lp_tokens: BN;
}

export interface WithdrawStakeParams {
  pendingActivation: boolean;
  deactivated: boolean;
}

export interface WithdrawTokenLog {
  owner: PublicKey;
  token_stake: PublicKey;
  withdraw_amount: BN;
  current_timestamp: BN;
  last_updated_timestamp: BN;
  level: number;
  active_stake_amount: BN;
}

export interface WithdrawTokenParams {
  withdrawRequestId: number;
}

export interface WithdrawUnclaimedTokensParams {
}

// ============ Event Type Aliases ============
// Event types use snake_case field names (Anchor v0.32 convention)
// Event types are defined in the types section above (names ending in "Log")
